FROM mcr.microsoft.com/playwright/python:v1.48.0-jammy AS build-image

ARG LAMBDA_TASK_ROOT="/var/task"
RUN mkdir -p ${LAMBDA_TASK_ROOT}
WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip install --target ${LAMBDA_TASK_ROOT} -r requirements.txt awslambdaric

# Add the RIE for local testing
ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/local/bin/aws-lambda-rie
RUN chmod +x /usr/local/bin/aws-lambda-rie

COPY DTOs/ ${LAMBDA_TASK_ROOT}/DTOs/
COPY Clients/ ${LAMBDA_TASK_ROOT}/Clients/
COPY Skus/ ${LAMBDA_TASK_ROOT}/Skus/
COPY lambda_function.py ${LAMBDA_TASK_ROOT}/

ENTRYPOINT ["/usr/local/bin/aws-lambda-rie", "python", "-m", "awslambdaric"]
CMD ["lambda_function.handler"]